### ISSUE TITLE
[Request] Whitelist conversations and new .json

### ISSUE THREAD

**Issue by zeus1921** [Ashilles/Instagram-DM-Cleaner#3]
There should be an option in config.json so we can add some conversations/groups IDS so the bot won't delete it.

```
Login: {"username":"xxxxxxxx","password":"xxxxxxxxxxxxxxxx"}
Whitelist: {"340282366841710300949128126067268327149", "340282366841710300949128138828922852093"}
delete-groups: false (if possible)
```

Also, change the saved login data to config.json so it wont use one extra useless .json

**Comment by ahmedbkd** [comment]
Thanks for your suggestion,

I already planned this idea but didn't have time to do it.
After making some [changes](https://github.com/Ashilles/Instagram-DM-Cleaner/commit/a68c35be7c1c485c0f8e961979499f04236a8fdc) i forgot to save the login data in config.json.
