### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by zeus1921** [Ashilles/Instagram-DM-Cleaner#4]
hey there.
Whats wrong here? 

{
    "whitelist": [340282366841710300949128485012466376448,340282366841710300949128119403889452685],
    "sleep_time": 1.3,
    "filter_whitelist":true,
    "delete_groups": false
}

Like this, the script dsnt work 
![imagem](https://user-images.githubusercontent.com/28808082/186408036-164ac58f-f2c3-4277-9b71-028fa6d7fbc0.png)

**Comment by ahmedbkd** [comment]
`filter_whitelist` setting is meant to do the opposite of whitelisting, it only deletes the specified id's in the whitelist and avoid the rest of the DMs. It's confusing but with further updates it will be changed.

**Comment by zeus1921** [comment]
with **"delete_groups": false** the script is deleting them :(

**Comment by ahmedbkd** [comment]
I'm not sure if I can fix the issue at this point, but if you're interested in this project, contributions are always welcome. I will keep this issue open until it is fixed.
